spring.application.name=springboot-email-listener

spring.mail.host=imap.gmail.com
spring.mail.port=993
spring.mail.protocol=imaps
spring.mail.username=kursatsimsekodevler@gmail.com
spring.mail.password=pbuadcyiqztajvrs

spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/handleMail?allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=5858
spring.jpa.hibernate.ddl-auto=update